import "./globals.css";

import { cookies } from "next/headers";

import { ThemeToggle } from "@/components/theme";
import { Sidebar, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

import type { LayoutProps } from "@/types/next";
import type { Metadata } from "next";

export const metadata: Metadata = {
	description: "Generated by create next app",
	title: "Create Next App",
};

export default async function RootLayout({ children }: LayoutProps) {
	const cookiesStore = await cookies();
	const theme = cookiesStore.get("theme")?.value === "dark" ? "dark" : undefined;
	const sidebarState = cookiesStore.get("sidebar:state")?.value === "true";

	return (
		<html className={theme} lang="en">
			<body>
				<SidebarProvider defaultOpen={sidebarState}>
					<Sidebar></Sidebar>
					<div className="grid size-full grid-rows-[auto_1fr_auto]">
						<header className="flex h-14 w-full items-center justify-between border-b border-border px-8 py-2.5">
							<SidebarTrigger />
							<ThemeToggle theme={theme} />
						</header>
						<main className="py-4 container">{children}</main>
						<footer className="flex h-14 items-center px-8 py-2.5 text-xs text-foreground/60">
							<div className="flex gap-2.5">
								<p>
									&copy; Design by{" "}
									<a
										className="underline"
										href="https://github.com/nathanaeld01"
										rel="noreferrer"
										target="_blank"
									>
										Nathanael D&apos;Cunha
									</a>
								</p>
								<p>•</p>
								<p>
									Components by{" "}
									<a
										className="underline"
										href="https://ui.shadcn.com"
										rel="noreferrer"
										target="_blank"
									>
										shadcn
									</a>
								</p>
							</div>
						</footer>
					</div>
				</SidebarProvider>
			</body>
		</html>
	);
}
